# Generated by Django 4.2.5 on 2023-09-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Pno', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=13)),
                ('timeDate', models.DateTimeField(blank=True)),
            ],
        ),
    ]
