# Generated by Django 4.2.5 on 2023-09-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contents',
        ),
    ]
